# 1. La dirección de la bodega (URL de conexión a la base que creamos en Workbench)
spring.datasource.url=jdbc:mysql://localhost:3306/bolsaempleo?serverTimezone=UTC

# 2. Las llaves de la bodega (credenciales de MySQL.)
spring.datasource.username=root
spring.datasource.password=root

# 3. El conductor del camión (El driver de MySQL)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Comportamiento de Hibernate (¡SÚPER IMPORTANTE!)
# 'update' le dice a Spring que si las clases Java cambian, modifique las tablas de MySQL automáticamente.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

